import { useEffect, useState } from "react";
import type { Case } from "./types";
import { CaseState } from "./Guide";
import catalog from "../../../docs/evidence/model-guide.json";

type Row={id:string;family:string;condition:string;conversation_id:number|null;checkpoint:number|null;gold:string};
type Answer={model_id:string;status:string;selected:string|null;input_tokens:number|null;request_ms:number|null;probabilities:Record<string,number>|null};
async function get<T>(path:string,signal:AbortSignal):Promise<T>{
 const r=await fetch(path,{signal});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Unable to read saved ABCD data");return d;
}
function ConversationState({text}:{text:string}){
 const marker="OBSERVED CONVERSATION SO FAR\n",i=text.indexOf(marker);
 if(i<0)return <CaseState text={text}/>;
 const policy=text.slice(0,i),history=text.slice(i+marker.length);
 return <div className="structured-state"><h3>Conversation visible to the model</h3><p className="small muted">Only the saved history before this checkpoint. Later messages and the answer key were not part of the model input.</p><div className="conversation-turns">{history.split(/\n(?=(?:agent|customer|action):)/).map((turn,n)=>{const colon=turn.indexOf(":");return <div key={n}><b>{colon>=0?turn.slice(0,colon):"History"}</b><p>{colon>=0?turn.slice(colon+1):turn}</p></div>})}</div><details className="explain"><summary>Policy supplied to the model · {policy.length.toLocaleString()} characters</summary><pre className="policy-text">{policy}</pre></details><details className="explain"><summary>Exact saved state text</summary><pre className="policy-text">{text}</pre></details></div>
}
export function ABCDCases({offline}:{offline:boolean}){
 const [condition,setCondition]=useState(""),[task,setTask]=useState("route"),[conversation,setConversation]=useState(""),[offset,setOffset]=useState(0),[chosen,setChosen]=useState("");
 const [data,setData]=useState<{total:number;cases:Row[]}|null>(null),[detail,setDetail]=useState<{case:Case;predictions:Answer[]}|null>(null),[error,setError]=useState("");
 useEffect(()=>{if(offline)return;const ctl=new AbortController();setData(null);setDetail(null);setChosen("");setError("");const q=new URLSearchParams({condition,task,offset:String(offset),limit:"50"});if(conversation)q.set("conversation",conversation);get<{total:number;cases:Row[]}>("/api/abcd/cases?"+q,ctl.signal).then(x=>{setData(x);setChosen(x.cases[0]?.id||"")}).catch(e=>{if(e.name!=="AbortError")setError(e.message)});return()=>ctl.abort()},[condition,task,conversation,offset,offline]);
 useEffect(()=>{if(offline||!chosen)return;const ctl=new AbortController();setDetail(null);get<{case:Case;predictions:Answer[]}>("/api/abcd/cases/"+encodeURIComponent(chosen),ctl.signal).then(setDetail).catch(e=>{if(e.name!=="AbortError")setError(e.message)});return()=>ctl.abort()},[chosen,offline]);
 if(offline)return <section className="analysis-panel"><h2>ABCD case text stays in the local workspace</h2><p>The portable report contains aggregate results. Open the live Arena app on the machine holding the saved assessment to browse conversations, policies and model responses. Original dataset text is not bundled into this public report.</p></section>;
 const c=detail?.case;
 return <section><p>Frozen ABCD assessment · 300 conversations, 2,400 natural input variants and 144 separate synthetic controls. Each model has up to 2,544 saved records. Browsing makes no model calls.</p><div className="abcd-controls"><label>Policy input<select disabled={task==="synthetic_action"} value={condition} onChange={e=>{setCondition(e.target.value);setOffset(0)}}><option value="">Both policy conditions</option><option value="full_handbook">Full handbook</option><option value="retrieved_policy">Retrieved policy</option></select></label><label>Decision type<select value={task} onChange={e=>{setTask(e.target.value);setCondition("");setConversation("");setOffset(0)}}><option value="route">Act, speak or finish</option><option value="action">Choose among all 30 actions</option><option value="synthetic_action">Synthetic context control</option></select></label><label>Conversation ID<input type="number" min="0" value={conversation} placeholder="All conversations" onChange={e=>{setConversation(e.target.value);setOffset(0)}}/></label></div>{error&&<p role="alert">{error}</p>}
 <div className="case-workspace"><aside className="case-list"><div className="case-list-items">{data?.cases.map(x=><button key={x.id} className={chosen===x.id?"selected":""} onClick={()=>setChosen(x.id)}><span>{x.conversation_id==null?"Synthetic control":"Conversation "+x.conversation_id}<small>{x.condition?.replaceAll("_"," ")} · checkpoint {x.checkpoint??"—"}</small><small>{x.id}</small></span></button>)}</div>{data&&<div className="pagination"><button disabled={!offset} onClick={()=>setOffset(offset-50)}>Previous ABCD cases</button><span>{data.total?offset+1:0}–{Math.min(offset+50,data.total)} / {data.total}</span><button disabled={offset+50>=data.total} onClick={()=>setOffset(offset+50)}>Next ABCD cases</button></div>}</aside><section className="case-detail">{c?<><div className="eyebrow">{c.id}</div><h2>{c.question.text}</h2><div className="case-tags"><span className="tag">{c.family==="synthetic_action"?"SYNTHETIC CONTROL":"DATASET NEXT-STEP REFERENCE"}</span></div><ConversationState text={c.state}/><details className="explain"><summary>Allowed choices · {c.question.labels.length}</summary><ul>{c.question.labels.map(x=><li key={x}>{x}</li>)}</ul></details><div className="reference"><span>Reference answer · scoring only</span><strong>{c.gold}</strong></div><p className="small muted">The reference is the recorded dataset decision (or the declared synthetic rule), not proof that it is the only reasonable next step. End-of-conversation checkpoints were synthesized.</p><h3>Saved model responses</h3><div className="table-scroll"><table><thead><tr><th>Model</th><th>Selected answer</th><th>Answer matches</th><th>Output status</th><th>Input tokens</th><th>Request time</th></tr></thead><tbody>{detail?.predictions.map(p=><tr key={p.model_id}><td>{catalog.models.find(m=>m.id===p.model_id)?.name||p.model_id}</td><td>{p.selected||"—"}</td><td>{p.status==="unsupported"?"Unavailable":p.selected===c.gold?"Yes":"No"}</td><td>{p.status==="ok"?"Passed checks":p.status.replaceAll("_"," ")}</td><td>{p.input_tokens?.toLocaleString()??"Unknown"}</td><td>{p.status==="unsupported"||p.request_ms==null?"—":Math.round(p.request_ms)+" ms"}</td></tr>)}</tbody></table></div><details className="explain"><summary>Reference provenance · not supplied as input</summary><pre className="policy-text">{JSON.stringify(c.provenance,null,2)}</pre></details></>:<p>{data?.total===0?"No cases match these filters.":"Loading saved cases…"}</p>}</section></div></section>
}
